# Generated by Django 5.2.13 on 2026-04-19 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PluginConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plugin_id", models.CharField(db_index=True, max_length=100)),
                ("is_enabled", models.BooleanField(default=True)),
                ("_config_encrypted", models.BinaryField()),
            ],
            options={
                "unique_together": {("plugin_id",)},
            },
        ),
    ]
