# Generated by Django 5.2.13 on 2026-04-19 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("slack", "Slack Webhook"),
                            ("email", "Email"),
                            ("webhook", "Generic Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notify_on_open", models.BooleanField(default=True)),
                ("notify_on_resolve", models.BooleanField(default=True)),
                (
                    "min_severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
